name: pr

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - uses: actions-rs/toolchain@v1.0.7
        with:
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          sharedKey: debug-build
      - run: just test
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@v2
        with:
          tool: just
      - run: |
          echo "RUST_TOOLCHAIN_NIGHTLY=$(cat ./rust-toolchain-nightly)" >> $GITHUB_ENV
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_NIGHTLY }}
          components: rustfmt
      - uses: actions-rs/toolchain@v1.0.7
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          sharedKey: debug-build-nightly
      - run: just lint "strict"
