name: pr

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - uses: actions-rs/toolchain@v1.0.7
        with:
          override: true
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
        with:
          sharedKey: debug-build
      - run: make test
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-protoc@v1
        with:
          version: '3.x'
      - run: |
          echo "RUST_TOOLCHAIN_NIGHTLY=$(cat ./rust-toolchain-nightly)" >> $GITHUB_ENV
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN_NIGHTLY }}
          components: rustfmt
      - uses: actions-rs/toolchain@v1.0.7
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
        with:
          sharedKey: debug-build-nightly
      - run: make lint
